### ISSUE TITLE
Problems finding modules and importing them

### ISSUE THREAD

**Issue by keikojima02** [LSaldyt/bitflow#4]
When running ./run config/default.json with "bitflow:whitelist" : ["WikipediaModule"]}, "WikipediaModule.py" must be placed in "Modules" directory so that the get_module_names() function to be able to find "WikipediaModule.py".

Once get_module_names() can find "WikipediaModule.py", utils.py give the error message below:
TypeError: the 'package' argument is required to perform a relative import for './.modules.WikipediaModule'

Anaconda3
Python 3.7.6neo4j
neo4j 4.0.0

![ErrorMessage](https://user-images.githubusercontent.com/57758994/85336990-a5124000-b4ad-11ea-8ea2-cea9c7994073.PNG)

**Comment by LSaldyt** [comment]
What version of bitflow are you using? The path "./.modules" is wrong. It should be creating ".modules.WikipediaModule", but also it generally looks for modules in a *subdirectory* of modules (until the most recent version)

**Comment by keikojima02** [comment]
bitflow version 0.6.0 worked!
